### PR TITLE
Community code sync for operand, update CRDs

### PR DESCRIPTION
**Pull request by bluzarraga**

### CODE REVIEW

**Comment by bluzarraga** [comment]
The problem with the build comes from this line here: https://github.com/IBM/ibm-cert-manager-operator/blob/master/controllers/operator/suite_test.go#L29. This package is no longer included in controller-runtime past 0.13.1 (latest 0.16.2). I have no idea what the relevant code does https://github.com/IBM/ibm-cert-manager-operator/blob/master/controllers/operator/suite_test.go#L49 but this is the only place in the operator where this code is used. I tried finding replacement code from the community but it looks like they just completely stripped it out without replacement based on https://github.com/kubernetes-sigs/controller-runtime/pull/1977. I tried just setting the level of controller-runtime to 0.13.1 but that has caused the above build failures. Will need to look into this more, not sure what disabling that code would do for our testing/build process.

**Comment by bitscuit** [comment]
Please see the PR I have opened to update the controller-runtime and get it merged in first https://github.com/IBM/ibm-cert-manager-operator/pull/373. It should make this PR a lot easier and cleaner.

**Comment by bluzarraga** [comment]
This is 100% because of the changes to the operator suite_test.go file https://github.com/IBM/ibm-cert-manager-operator/pull/373/files#diff-9e9b69fa6c24f24eeac3c5817dd0cfe19d34194e179fac21090a522d74a2dbe5R47:
```
   /home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/controllers/operator/suite_test.go:60
------------------------------
Ran 0 of 0 Specs in 5.570 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
--- FAIL: TestAPIs (5.57s)
FAIL
	github.com/ibm/ibm-cert-manager-operator/controllers/operator	coverage: 0.0% of statements
FAIL	github.com/ibm/ibm-cert-manager-operator/controllers/operator	5.589s
FAIL
```
I was trying to make the exact same change in this PR prior to merging in 373 and was curious if it would be problematic. From the output of the test, it does not look like anything ran but it still is marked as a failure. We need to figure out how to replace this but unfortunately, as I mentioned in an earlier comment, the previous way we ran this test was deprecated but not replaced so we will need a new approach to this test.

**Review by bitscuit — CHANGES_REQUESTED** [review]
Change the labels back for all the CRD yamls. It's blocking the test because when I ran the test locally I got more logs

```
Unexpected error:
      <*fmt.wrapError | 0xc0000ac240>: 
      unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "challenges.acme.cert-manager.io": CustomResourceDefinition.apiextensions.k8s.io "challenges.acme.cert-manager.io" is invalid: [metadata.labels: Invalid value: "{{ template \"cert-manager.name\" . }}"
```

**Comment by bitscuit** [comment]
Also make sure the run `make manifests`, `make generate`, and `make bundle` to regenerate things properly.

**Comment by bluzarraga** [comment]
Those changes seem to have satisfied the build, thank you @bitscuit

**Review by bitscuit — APPROVED** [review]
/lgtm

**Pull request merged**
